mywebsite/mymusic/urls.py
from django.conf.urls import url
from . import views


app_name='mymusic'
urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail'),
    #mymusic/album_id/favorite
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

mywebsite/mywebsite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mymusic/',include('mymusic.urls'))
]

mywebsite/mymusic/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Album(models.Model):
    album_title=models.CharField(max_length=100)
    artist=models.CharField(max_length=100)
    genre=models.CharField(max_length = 100)
    album_logo=models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + '-' + self.genre

class Song(models.Model):
    album=models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=100)
    is_favorite=models.BooleanField(default='False')

    def __str__(self):
        return self.song_title

mywebsite/mymusic/views.py
from django.shortcuts import render
from django.http import Http404
from .models import Album,Song
from django.shortcuts import render, get_object_or_404
# Create your views here.

def index(request):
    all_albums = Album.objects.all()

    return render(request,'mymusic/index.html',{"all_albums": all_albums})

def detail(request,album_id):
    #try:
    #   album=Album.objects.get(pk=album_id)
    #except Album.DoesNotExist:
    #   raise Http404("Album doses not exist")
    album=get_object_or_404(Album,pk=album_id)
    return render(request,'mymusic/detail.html',{"album" : album})

def favorite(request,album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song=album.song_set.get(pk=request.POST['song'])
    except(KeyError,Song.DoesNotExist):
        return render(request, 'mymusic/detail.html',
                      {"album": album},
                      {'erroe_message': 'you didnt select a valid song'},)
    else:
        selected_song.is_favorite=True
        selected_song.save()
        return render(request, 'mymusic/detail.html', {"album": album})

mywebsite/mymusic/templates/mymusic/detail.html
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }} </h1>
<h2>{{ album.artist }}</h2>

{% if error_message %}
    <p><strong> {{ error_message }}</strong></p>
{% endif %}
<form action=" {% url 'mymusic:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}"  name="song" value="{{ song.id }}"/>
        <label for ="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png"/>
            {% endif %}
        </label><br>
    {% endfor %}
    <input type = "submit" value="Favorite">
</form>

mywebsite/mymusic/templates/mymusic/index.html
{% if all_albums %}

    <ul>
        {% for album in all_albums %}
        <li> <a href =" {% url 'mymusic:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}

    <h2> you dont have anything to select</h2>

{%  endif %}